// app/components/LandingPage.tsx
import Link from 'next/link'
import {
  ArrowRight,
  Zap,
  Shield,
  BarChart,
  Rocket,
  Github,
  CheckCircle2,
  Code,
  Globe
} from 'lucide-react'

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-slate-50 text-slate-950 font-sans overflow-hidden selection:bg-emerald-200 selection:text-emerald-900">

      {/* --- Background Pattern --- */}
      <div className="fixed inset-0 z-0 pointer-events-none opacity-40">
        <div className="absolute inset-0 bg-[radial-gradient(#e5e7eb_1px,transparent_1px)] [background-size:16px_16px] [mask-image:radial-gradient(ellipse_50%_50%_at_50%_50%,#000_70%,transparent_100%)]"></div>
      </div>

      {/* --- Navbar --- */}
      <nav className="sticky top-0 z-50 w-full border-b border-slate-200/60 bg-white/70 backdrop-blur-md">
        <div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">

          {/* Logo */}
          <Link href="/auth" className="flex items-center gap-2 font-bold text-xl tracking-tight group">
            <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-emerald-500 to-teal-600 flex items-center justify-center text-white shadow-lg group-hover:scale-105 group-hover:shadow-xl transition-all duration-300">
              <Zap className="w-4 h-4 fill-current" />
            </div>
            <span className="text-slate-900 group-hover:text-emerald-600 transition-colors">DKS QwikPlan</span>
          </Link>

          {/* Desktop Nav */}
          <div className="hidden md:flex items-center gap-8 text-sm font-medium text-slate-600">
            <Link href="#features" className="hover:text-slate-900 hover:text-emerald-600 transition-colors relative group">
              Features
              <span className="absolute bottom-0 left-0 w-0 h-0.5 bg-emerald-600 transition-all duration-300 group-hover:w-full"></span>
            </Link>
            <Link href="https://github.com/seenuraj2007/kds_qwikplan" target="_blank" className="hover:text-slate-900 hover:text-emerald-600 transition-colors flex items-center gap-1.5 group">
              <Github className="w-4 h-4 group-hover:scale-110 transition-transform" /> GitHub
            </Link>
          </div>

          {/* CTA */}
          <div className="flex items-center gap-3">
            <Link
              href="/auth"
              className="inline-flex items-center justify-center px-5 py-2 text-sm font-semibold text-white bg-slate-900 rounded-lg hover:bg-slate-800 transition-all shadow-lg hover:shadow-xl hover:-translate-y-0.5 active:translate-y-0"
            >
              Get Started
            </Link>
          </div>
        </div>
      </nav>

      {/* --- Hero Section --- */}
      <main className="relative pt-24 pb-16 sm:pt-32 sm:pb-24 z-10">
        <div className="max-w-7xl mx-auto px-6 text-center">

          {/* Badge */}
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-emerald-50 border border-emerald-100 text-emerald-700 text-xs font-bold uppercase tracking-wider mb-8 animate-fade-in-up">
            <span className="relative flex h-2 w-2">
              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75"></span>
              <span className="relative inline-flex rounded-full h-2 w-2 bg-emerald-500"></span>
            </span>
            V 1.0 Beta is now live
          </div>

          {/* Heading */}
          <h1 className="text-5xl md:text-7xl font-extrabold tracking-tight text-slate-900 mb-6 animate-slide-in-up">
            Marketing Strategies <br className="hidden md:block" />
            Generated by <span className="text-transparent bg-clip-text bg-gradient-to-r from-emerald-600 to-teal-500">Artificial Intelligence</span>
          </h1>

          {/* Subheading */}
          <p className="max-w-2xl mx-auto text-lg md:text-xl text-slate-600 mb-10 leading-relaxed animate-slide-in-up" style={{animationDelay: '100ms'}}>
            Stop struggling with content plans. KDS QwikPlan analyzes your niche and generates actionable marketing roadmaps in seconds. Open source and developer friendly.
          </p>

          {/* Buttons */}
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4 mb-20 animate-slide-in-up" style={{animationDelay: '200ms'}}>
            <Link
              href="/auth"
              className="w-full sm:w-auto flex items-center justify-center gap-2 h-12 px-8 rounded-xl font-bold text-white bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-700 hover:to-teal-700 shadow-lg shadow-emerald-500/25 transition-all transform hover:scale-105 hover:shadow-xl hover:shadow-emerald-500/40"
            >
              Start Generating Free <ArrowRight className="w-4 h-4" />
            </Link>

            <Link
              href="https://github.com/seenuraj2007/kds_qwikplan"
              target="_blank"
              className="w-full sm:w-auto flex items-center justify-center gap-2 h-12 px-8 rounded-xl font-bold text-slate-700 bg-white border border-slate-200 hover:bg-slate-50 hover:border-slate-300 hover:text-slate-900 transition-all shadow-sm hover:shadow-md"
            >
              <Github className="w-5 h-5" />
              Star on GitHub
            </Link>
          </div>

{/* Dashboard Preview Card - Responsive to Image Size */}
<div className="relative max-w-5xl mx-auto group animate-slide-in-up" style={{animationDelay: '300ms'}}>
<div className="absolute -inset-1 bg-gradient-to-r from-emerald-600 to-teal-600 rounded-2xl blur opacity-25 group-hover:opacity-50 transition duration-1000 group-hover:duration-200"></div>
<div className="relative bg-slate-900 rounded-xl ring-1 ring-white/10 shadow-2xl overflow-hidden flex items-center justify-center border border-slate-800 transform transition-transform duration-300 group-hover:scale-[1.02]">
{/*
NOTE: Replace the 'src' below with your actual screenshot path.
E.g., if your file is in the 'public' folder: src="/screenshot.png"
*/}
<img
src="/Screenshot 2025-12-31 at 11.36.41 PM"
alt="AI Marketing Generator Dashboard Interface"
className="w-full h-auto block"
/>
</div>
</div>
</div>
</main>

      {/* --- Bento Grid Features --- */}
      <section id="features" className="py-16 max-w-7xl mx-auto px-6">
        <div className="text-center mb-16">
          <h2 className="text-3xl md:text-4xl font-bold text-slate-900 mb-4 animate-slide-in-up">Everything you need to grow</h2>
          <p className="text-lg text-slate-600 animate-slide-in-up" style={{animationDelay: '100ms'}}>Powerful tools packed into one simple interface.</p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">

          {/* Feature 1 (Large) */}
          <div className="md:col-span-2 p-8 rounded-3xl bg-white border border-slate-200 shadow-sm hover:shadow-xl hover:border-emerald-300 transition-all duration-300 group overflow-hidden relative transform hover:-translate-y-1">
            <div className="absolute top-0 right-0 p-8 opacity-5 group-hover:opacity-10 transition-opacity duration-300 transform group-hover:scale-110">
               <Zap className="w-48 h-48" />
            </div>
            <div className="w-12 h-12 rounded-xl bg-emerald-100 text-emerald-600 flex items-center justify-center mb-6 group-hover:bg-emerald-600 group-hover:text-white transition-colors duration-300">
              <Zap className="w-6 h-6" />
            </div>
            <h3 className="text-2xl font-bold text-slate-900 mb-3 group-hover:text-emerald-600 transition-colors">AI Generation Engine</h3>
            <p className="text-slate-600 text-lg leading-relaxed max-w-md">
              Our proprietary AI analyzes current market trends and generates a full marketing strategy tailored to your niche in under 5 seconds.
            </p>
          </div>

          {/* Feature 2 */}
          <div className="p-8 rounded-3xl bg-white border border-slate-200 shadow-sm hover:shadow-xl hover:border-blue-300 transition-all duration-300 group transform hover:-translate-y-1">
            <div className="w-12 h-12 rounded-xl bg-blue-100 text-blue-600 flex items-center justify-center mb-6 group-hover:bg-blue-600 group-hover:text-white transition-colors duration-300">
              <BarChart className="w-6 h-6" />
            </div>
            <h3 className="text-xl font-bold text-slate-900 mb-3 group-hover:text-blue-600 transition-colors">Data Driven</h3>
            <p className="text-slate-600">
              Strategies based on real platform performance metrics and audience behavior data.
            </p>
          </div>

          {/* Feature 3 */}
          <div className="p-8 rounded-3xl bg-white border border-slate-200 shadow-sm hover:shadow-xl hover:border-purple-300 transition-all duration-300 group transform hover:-translate-y-1">
            <div className="w-12 h-12 rounded-xl bg-purple-100 text-purple-600 flex items-center justify-center mb-6 group-hover:bg-purple-600 group-hover:text-white transition-colors duration-300">
              <Shield className="w-6 h-6" />
            </div>
            <h3 className="text-xl font-bold text-slate-900 mb-3 group-hover:text-purple-600 transition-colors">Secure First</h3>
            <p className="text-slate-600">
              Enterprise-grade security. We ensure your business data remains private and encrypted.
            </p>
          </div>

          {/* Feature 4 (Large) */}
          <div className="md:col-span-2 p-8 rounded-3xl bg-slate-900 text-white shadow-lg hover:shadow-2xl transition-all duration-300 overflow-hidden relative transform hover:-translate-y-1 group">
            <div className="absolute top-0 right-0 w-full h-full bg-[radial-gradient(circle_at_top_right,_var(--tw-gradient-stops))] from-emerald-900/50 to-transparent opacity-50 group-hover:opacity-70 transition-opacity duration-300"></div>
            <div className="relative z-10 flex flex-col md:flex-row items-center gap-8">
              <div className="flex-1">
                <h3 className="text-2xl font-bold mb-3">Open Source Code</h3>
                <p className="text-slate-300 mb-6">
                  We believe in transparency. View our codebase, contribute, or host it on your own server. Fully customizable.
                </p>
                <Link
                  href="https://github.com/seenuraj2007/kds_qwikplan"
                  target="_blank"
                  className="inline-flex items-center gap-2 px-6 py-3 bg-white text-slate-900 rounded-lg font-bold hover:bg-emerald-50 transition-all duration-300 hover:shadow-lg hover:shadow-emerald-500/20"
                >
                  <Github className="w-4 h-4" /> View Source Code
                </Link>
              </div>
              <div className="flex-1 font-mono text-xs text-emerald-400 bg-black/50 p-4 rounded-lg border border-white/10">
                 <span className="text-pink-400">const</span> config = &#123;<br/>
                  &nbsp;&nbsp;apiKey: <span className="text-yellow-300">&quot;...&quot;</span>,<br/>
                  &nbsp;&nbsp;mode: <span className="text-yellow-300">&quot;aggressive&quot;</span>,<br/>
                  &nbsp;&nbsp;platform: <span className="text-yellow-300">&quot;instagram&quot;</span><br/>
                  &#125;;<br/>
                  <br/>
                  <span className="text-pink-400">await</span> generate(config);
              </div>
            </div>
          </div>

        </div>
      </section>



      {/* --- CTA Section --- */}
      <section className="py-20 bg-slate-900 relative overflow-hidden">
        <div className="absolute inset-0">
          <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-96 h-96 bg-emerald-500/10 rounded-full blur-3xl"></div>
        </div>
        <div className="relative max-w-3xl mx-auto px-6 text-center">
          <h2 className="text-3xl md:text-4xl font-bold text-white mb-6 animate-slide-in-up">
            Ready to Grow Your Business?
          </h2>
          <p className="text-lg text-slate-400 mb-8 animate-slide-in-up" style={{animationDelay: '100ms'}}>
DKS QwikPlan to create powerful marketing strategies in seconds.
          </p>
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4 animate-slide-in-up" style={{animationDelay: '200ms'}}>
            <Link
              href="/auth"
              className="w-full sm:w-auto inline-flex items-center justify-center gap-2 h-12 px-8 rounded-xl font-bold text-white bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-700 hover:to-teal-700 shadow-lg shadow-emerald-500/30 transition-all transform hover:scale-105 hover:shadow-xl"
            >
              Get Started Free <Rocket className="w-4 h-4" />
            </Link>
          </div>
        </div>
      </section>

      {/* --- Footer --- */}
      <footer className="bg-white border-t border-slate-200 py-12">
        <div className="max-w-7xl mx-auto px-6 flex flex-col md:flex-row justify-between items-center gap-6">
          <div className="flex items-center gap-2">
            <span className="font-bold text-slate-900">DKS QwikPlan</span>
          </div>

          <div className="flex gap-6 text-sm font-medium text-slate-600">
            <Link href="/auth" className="hover:text-emerald-600 transition relative group">
              Product
              <span className="absolute bottom-0 left-0 w-0 h-0.5 bg-emerald-600 transition-all duration-300 group-hover:w-full"></span>
            </Link>
            <Link href="https://github.com/seenuraj2007/kds_qwikplan" target="_blank" className="hover:text-emerald-600 transition relative group">
              GitHub
              <span className="absolute bottom-0 left-0 w-0 h-0.5 bg-emerald-600 transition-all duration-300 group-hover:w-full"></span>
            </Link>
          </div>

          <div className="text-sm text-slate-400">
            &copy; {new Date().getFullYear()} DKS QwikPlan.
          </div>
        </div>
      </footer>

    </div>
  )
}
