// app/components/LandingPage.jsx
import Link from 'next/link'
import { 
  ArrowRight, 
  Zap, 
  Shield, 
  BarChart, 
  Rocket, 
  Github,
  CheckCircle2,
  Code,
  Globe
} from 'lucide-react'

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-slate-50 text-slate-950 font-sans overflow-hidden selection:bg-emerald-200 selection:text-emerald-900">
      
      {/* --- Background Pattern --- */}
      <div className="fixed inset-0 z-0 pointer-events-none opacity-40">
        <div className="absolute inset-0 bg-[radial-gradient(#e5e7eb_1px,transparent_1px)] [background-size:16px_16px] [mask-image:radial-gradient(ellipse_50%_50%_at_50%_50%,#000_70%,transparent_100%)]"></div>
      </div>

      {/* --- Navbar --- */}
      <nav className="sticky top-0 z-50 w-full border-b border-slate-200/60 bg-white/70 backdrop-blur-md">
        <div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
          
          {/* Logo */}
          <Link href="/auth" className="flex items-center gap-2 font-bold text-xl tracking-tight group">
            <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-emerald-500 to-teal-600 flex items-center justify-center text-white shadow-lg group-hover:scale-105 transition-transform">
              <Zap className="w-4 h-4 fill-current" />
            </div>
            <span className="text-slate-900">KDS QwikPlan</span>
          </Link>

          {/* Desktop Nav */}
          <div className="hidden md:flex items-center gap-8 text-sm font-medium text-slate-600">
            {/* <Link href="#features" className="hover:text-emerald-600 transition-colors">Features</Link>
            <Link href="#pricing" className="hover:text-emerald-600 transition-colors">Pricing</Link> */}
            <Link href="https://github.com/seenuraj2007/kds_qwikplan" target="_blank" className="hover:text-slate-900 transition-colors flex items-center gap-1">
              <Github className="w-4 h-4" /> GitHub
            </Link>
          </div>

          {/* CTA */}
          <div className="flex items-center gap-3">
            {/* <Link href="/auth" className="hidden sm:inline-flex items-center justify-center px-4 py-2 text-sm font-semibold text-slate-700 bg-white border border-slate-200 rounded-lg hover:bg-slate-50 hover:text-emerald-600 transition-all shadow-sm">
              Log In
            </Link> */}
            <Link 
              href="/auth" 
              className="inline-flex items-center justify-center px-4 py-2 text-sm font-semibold text-white bg-slate-900 rounded-lg hover:bg-slate-800 transition-all shadow-lg hover:shadow-xl hover:-translate-y-0.5"
            >
              Get Started
            </Link>
          </div>
        </div>
      </nav>

      {/* --- Hero Section --- */}
      <main className="relative pt-24 pb-16 sm:pt-32 sm:pb-24 z-10">
        <div className="max-w-7xl mx-auto px-6 text-center">
          
          {/* Badge */}
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-emerald-50 border border-emerald-100 text-emerald-700 text-xs font-bold uppercase tracking-wider mb-8 animate-fade-in-up">
            <span className="relative flex h-2 w-2">
              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75"></span>
              <span className="relative inline-flex rounded-full h-2 w-2 bg-emerald-500"></span>
            </span>
            V 1.0 Beta is now live
          </div>

          {/* Heading */}
          <h1 className="text-5xl md:text-7xl font-extrabold tracking-tight text-slate-900 mb-6">
            Marketing Strategies <br className="hidden md:block" />
            Generated by <span className="text-transparent bg-clip-text bg-gradient-to-r from-emerald-600 to-teal-500">Artificial Intelligence</span>
          </h1>

          {/* Subheading */}
          <p className="max-w-2xl mx-auto text-lg md:text-xl text-slate-600 mb-10 leading-relaxed">
            Stop struggling with content plans. KDS QwikPlan analyzes your niche and generates actionable marketing roadmaps in seconds. Open source and developer friendly.
          </p>

          {/* Buttons */}
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4 mb-20">
            <Link 
              href="/auth" 
              className="w-full sm:w-auto flex items-center justify-center gap-2 h-12 px-8 rounded-xl font-bold text-white bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-700 hover:to-teal-700 shadow-lg shadow-emerald-500/25 transition-all transform hover:scale-105"
            >
              Start Generating Free <ArrowRight className="w-4 h-4" />
            </Link>

            <Link 
              href="https://github.com/seenuraj2007/kds_qwikplan" 
              target="_blank"
              className="w-full sm:w-auto flex items-center justify-center gap-2 h-12 px-8 rounded-xl font-bold text-slate-700 bg-white border border-slate-200 hover:bg-slate-50 hover:border-slate-300 hover:text-slate-900 transition-all shadow-sm"
            >
              <Github className="w-5 h-5" />
              Star on GitHub
            </Link>
          </div>

          {/* Dashboard Preview Card */}
          <div className="relative max-w-5xl mx-auto group">
            <div className="absolute -inset-1 bg-gradient-to-r from-emerald-600 to-teal-600 rounded-2xl blur opacity-25 group-hover:opacity-50 transition duration-1000 group-hover:duration-200"></div>
            <div className="relative bg-slate-900 rounded-xl ring-1 ring-white/10 shadow-2xl overflow-hidden aspect-[16/9] md:aspect-[21/9] flex items-center justify-center border border-slate-800">
               {/* Mock UI Content */}
               <div className="text-slate-500 font-mono text-sm">
                 <div className="flex gap-2 mb-4">
                   <div className="h-3 w-3 rounded-full bg-red-500/20"></div>
                   <div className="h-3 w-3 rounded-full bg-yellow-500/20"></div>
                   <div className="h-3 w-3 rounded-full bg-green-500/20"></div>
                 </div>
                 <div className="grid grid-cols-12 gap-4 p-6 opacity-50">
                    <div className="col-span-3 h-32 bg-slate-800 rounded animate-pulse"></div>
                    <div className="col-span-9 space-y-4">
                       <div className="h-8 bg-slate-800 rounded animate-pulse"></div>
                       <div className="h-8 bg-slate-800 rounded animate-pulse w-3/4"></div>
                       <div className="grid grid-cols-3 gap-2 mt-4">
                          <div className="h-20 bg-slate-800 rounded animate-pulse"></div>
                          <div className="h-20 bg-slate-800 rounded animate-pulse"></div>
                          <div className="h-20 bg-slate-800 rounded animate-pulse"></div>
                       </div>
                    </div>
                 </div>
               </div>
            </div>
          </div>
        </div>
      </main>

      {/* --- Social Proof --- */}


      {/* --- Bento Grid Features --- */}
      <section id="features" className="py-10 max-w-7xl mx-auto px-6">
        <div className="text-center mb-16">
          <h2 className="text-3xl md:text-4xl font-bold text-slate-900 mb-4">Everything you need to grow</h2>
          <p className="text-lg text-slate-600">Powerful tools packed into one simple interface.</p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          
          {/* Feature 1 (Large) */}
          <div className="md:col-span-2 p-8 rounded-3xl bg-white border border-slate-200 shadow-sm hover:shadow-lg hover:border-emerald-200 transition-all group overflow-hidden relative">
            <div className="absolute top-0 right-0 p-8 opacity-10 group-hover:opacity-20 transition-opacity">
               <Zap className="w-48 h-48" />
            </div>
            <div className="w-12 h-12 rounded-xl bg-emerald-100 text-emerald-600 flex items-center justify-center mb-6">
              <Zap className="w-6 h-6" />
            </div>
            <h3 className="text-2xl font-bold text-slate-900 mb-3">AI Generation Engine</h3>
            <p className="text-slate-600 text-lg leading-relaxed max-w-md">
              Our proprietary AI analyzes current market trends and generates a full marketing strategy tailored to your niche in under 5 seconds.
            </p>
          </div>

          {/* Feature 2 */}
          <div className="p-8 rounded-3xl bg-white border border-slate-200 shadow-sm hover:shadow-lg hover:border-blue-200 transition-all group">
            <div className="w-12 h-12 rounded-xl bg-blue-100 text-blue-600 flex items-center justify-center mb-6">
              <BarChart className="w-6 h-6" />
            </div>
            <h3 className="text-xl font-bold text-slate-900 mb-3">Data Driven</h3>
            <p className="text-slate-600">
              Strategies based on real platform performance metrics and audience behavior data.
            </p>
          </div>

          {/* Feature 3 */}
          <div className="p-8 rounded-3xl bg-white border border-slate-200 shadow-sm hover:shadow-lg hover:border-purple-200 transition-all group">
            <div className="w-12 h-12 rounded-xl bg-purple-100 text-purple-600 flex items-center justify-center mb-6">
              <Shield className="w-6 h-6" />
            </div>
            <h3 className="text-xl font-bold text-slate-900 mb-3">Secure First</h3>
            <p className="text-slate-600">
              Enterprise-grade security. We ensure your business data remains private and encrypted.
            </p>
          </div>

          {/* Feature 4 (Large) */}
          <div className="md:col-span-2 p-8 rounded-3xl bg-slate-900 text-white shadow-lg hover:shadow-xl transition-all overflow-hidden relative">
            <div className="absolute top-0 right-0 w-full h-full bg-[radial-gradient(circle_at_top_right,_var(--tw-gradient-stops))] from-emerald-900/50 to-transparent opacity-50"></div>
            <div className="relative z-10 flex flex-col md:flex-row items-center gap-8">
              <div className="flex-1">
                <h3 className="text-2xl font-bold mb-3">Open Source Code</h3>
                <p className="text-slate-300 mb-6">
                  We believe in transparency. View our codebase, contribute, or host it on your own server. Fully customizable.
                </p>
                <Link 
                  href="https://github.com/seenuraj2007/kds_qwikplan" 
                  target="_blank"
                  className="inline-flex items-center gap-2 px-6 py-3 bg-white text-slate-900 rounded-lg font-bold hover:bg-slate-100 transition-colors"
                >
                  <Github className="w-4 h-4" /> View Source Code
                </Link>
              </div>
              <div className="flex-1 font-mono text-xs text-emerald-400 bg-black/50 p-4 rounded-lg border border-white/10">
                <span className="text-pink-400">const</span> config = &#123;<br/>
                 &nbsp;&nbsp;apiKey: <span className="text-yellow-300">&quot;...&quot;</span>,<br/>
                 &nbsp;&nbsp;mode: <span className="text-yellow-300">&quot;aggressive&quot;</span>,<br/>
                 &nbsp;&nbsp;platform: <span className="text-yellow-300">&quot;instagram&quot;</span><br/>
                 &#125;;<br/>
                 <br/>
                 <span className="text-pink-400">await</span> generate(config);
              </div>
            </div>
          </div>

        </div>
      </section>

      {/* --- Footer --- */}
      <footer className="bg-white border-t border-slate-200 py-12">
        <div className="max-w-7xl mx-auto px-6 flex flex-col md:flex-row justify-between items-center gap-6">
          <div className="flex items-center gap-2">
            <span className="font-bold text-slate-900">KDS QwikPlan</span>
          </div>
          
          <div className="flex gap-6 text-sm font-medium text-slate-600">
            <Link href="/auth" className="hover:text-emerald-600 transition">Product</Link>
            {/* <Link href="#" className="hover:text-emerald-600 transition">Documentation</Link> */}
            <Link href="https://github.com/seenuraj2007/kds_qwikplan" target="_blank" className="hover:text-emerald-600 transition">GitHub</Link>
          </div>
          
          <div className="text-sm text-slate-400">
            &copy; {new Date().getFullYear()} KDS QwikPlan.
          </div>
        </div>
      </footer>

    </div>
  )
}